version: "3.7"

services:
  jupyter:
    image: rivia/jupyterlab:db
    restart: always
    hostname: jupyter
    ports:
      - "1234:22"
      - "8888:8888"
      - "6379:6379"
    environment:
      ROOT_PASS: "jupyter"
      PASSWORD: "jupyter"
      WORK_DIR: "/root/share"
    volumes:
      - /root/share:/root/share
    depends_on:
      - influxdb
    container_name: jupyter-lab

  influxdb:
    image: influxdb:alpine
    restart: always
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: 'jupyter'
      INFLUXDB_USER: "root"
      INFLUXDB_USER_PASSWORD: "root"
    volumes:
      - /jupyter/influxdb:/var/lib/influxdb
    container_name: jupyter-influxdb
  
